# Problem 1

In [1]:
import numpy as np
matris = np.random.randint(0, 11, size=(1, 5))
print("Matris:", matris)
matrisboyutu = matris.shape
print("Matrisin Boyutu:", matrisboyutu)
yenimatris = matris.reshape(5, 1)
print("Yeniden Boyutlandırılmış Matris:\n", yenimatris)
boyutsayisi = yenimatris.ndim
print("Boyut Sayısı:", boyutsayisi)


Matris: [[3 6 7 7 2]]
Matrisin Boyutu: (1, 5)
Yeniden Boyutlandırılmış Matris:
 [[3]
 [6]
 [7]
 [7]
 [2]]
Boyut Sayısı: 2


# Problem 2

In [28]:
import numpy as np
teksayilar = np.arange(1, 11, 2)
matris = np.random.choice(teksayilar, size=(3, 4))
print("Matris:", matris)

parca1, parca2 = np.hsplit(matris, 2)
print("Parça 1:", parca1)
print("Parça 2:", parca2)

birlesmismatris = np.hstack((parca1, parca2))
print("Birleşmiş Matris:", birlesmismatris)



Matris: [[5 7 5 3]
 [1 5 1 7]
 [3 9 5 1]]
Parça 1: [[5 7]
 [1 5]
 [3 9]]
Parça 2: [[5 3]
 [1 7]
 [5 1]]
Birleşmiş Matris: [[5 7 5 3]
 [1 5 1 7]
 [3 9 5 1]]


# Problem 3

In [29]:
import numpy as np
sayilar = np.arange(5, 101, 2)
matris = np.random.choice(sayilar, size=(2, 5))
print("Matris:", matris)
boyut = matris.shape
print("\nMatrisin Boyutu:", boyut)
elemansayisi = matris.size
print("Matrisin Eleman Sayısı:", elemansayisi)
boyutsayisi = matris.ndim
print("Matrisin Boyut Sayısı:", boyutsayisi)
veritipi = matris.dtype
print("Matrisin Veri Tipi:", veritipi)
minimum_deger = np.min(matris)
maksimum_deger = np.max(matris)
print("Matrisin Minimum Değeri:", minimum_deger)
print("Matrisin Maksimum Değeri:", maksimum_deger)



Matris: [[97 11 67 49 61]
 [19 13 19 79 39]]

Matrisin Boyutu: (2, 5)
Matrisin Eleman Sayısı: 10
Matrisin Boyut Sayısı: 2
Matrisin Veri Tipi: int64
Matrisin Minimum Değeri: 11
Matrisin Maksimum Değeri: 97
